using System.Collections.Generic;
using System.Linq;

namespace LocalBitcoins
{
    public class Countries
    {
        public string Name { get; set; }
        public string Code { get; set; }

        public List<Countries> GetCountriesList()
        {
            var countriesList = new List<Countries>()
            {
                new Countries(){ Name="Anonymous Proxy", Code="A1"},
                new Countries(){ Name="Afghanistan", Code="AF"},
                new Countries(){ Name="Albania", Code="AL"},
                new Countries(){ Name="Algeria", Code="DZ"},
                new Countries(){ Name="American Samoa", Code="AS"},
                new Countries(){ Name="Andorra", Code="AD"},
                new Countries(){ Name="Angola", Code="AO"},
                new Countries(){ Name="Anguilla", Code="AI"},
                new Countries(){ Name="Antarctica", Code="AQ"},
                new Countries(){ Name="Antigua and Barbuda", Code="AG"},
                new Countries(){ Name="Argentina", Code="AR"},
                new Countries(){ Name="Armenia", Code="AM"},
                new Countries(){ Name="Aruba", Code="AW"},
                new Countries(){ Name="Australia", Code="AU"},
                new Countries(){ Name="Austria", Code="AT"},
                new Countries(){ Name="Azerbaijan", Code="AZ"},
                new Countries(){ Name="Bahamas", Code="BS"},
                new Countries(){ Name="Bahrain", Code="BH"},
                new Countries(){ Name="Bangladesh", Code="BD"},
                new Countries(){ Name="Barbados", Code="BB"},
                new Countries(){ Name="Belarus", Code="BY"},
                new Countries(){ Name="Belgium", Code="BE"},
                new Countries(){ Name="Belize", Code="BZ"},
                new Countries(){ Name="Benin", Code="BJ"},
                new Countries(){ Name="Bermuda", Code="BM"},
                new Countries(){ Name="Bhutan", Code="BT"},
                new Countries(){ Name="Bolivia", Code="BO"},
                new Countries(){ Name="Bosnia and Herzegovina", Code="BA"},
                new Countries(){ Name="Botswana", Code="BW"},
                new Countries(){ Name="Bouvet Island", Code="BV"},
                new Countries(){ Name="Brazil", Code="BR"},
                new Countries(){ Name="British Indian Ocean Territory", Code="IO"},
                new Countries(){ Name="Brunei Darussalam", Code="BN"},
                new Countries(){ Name="Bulgaria", Code="BG"},
                new Countries(){ Name="Burkina Faso", Code="BF"},
                new Countries(){ Name="Burundi", Code="BI"},
                new Countries(){ Name="Cambodia", Code="KH"},
                new Countries(){ Name="Cameroon", Code="CM"},
                new Countries(){ Name="Canada", Code="CA"},
                new Countries(){ Name="Cape Verde", Code="CV"},
                new Countries(){ Name="Cayman Islands", Code="KY"},
                new Countries(){ Name="Central African Republic", Code="CF"},
                new Countries(){ Name="Chad", Code="TD"},
                new Countries(){ Name="Chile", Code="CL"},
                new Countries(){ Name="China", Code="CN"},
                new Countries(){ Name="Christmas Island", Code="CX"},
                new Countries(){ Name="Cocos (Keeling) Islands", Code="CC"},
                new Countries(){ Name="Colombia", Code="CO"},
                new Countries(){ Name="Comoros", Code="KM"},
                new Countries(){ Name="Congo", Code="CG"},
                new Countries(){ Name="Congo, the Democratic Republic of the", Code="CD"},
                new Countries(){ Name="Cook Islands", Code="CK"},
                new Countries(){ Name="Costa Rica", Code="CR"},
                new Countries(){ Name="Cote D'Ivoire", Code="CI"},
                new Countries(){ Name="Croatia", Code="HR"},
                new Countries(){ Name="Cuba", Code="CU"},
                new Countries(){ Name="Cyprus", Code="CY"},
                new Countries(){ Name="Czech Republic", Code="CZ"},
                new Countries(){ Name="Denmark", Code="DK"},
                new Countries(){ Name="Djibouti", Code="DJ"},
                new Countries(){ Name="Dominica", Code="DM"},
                new Countries(){ Name="Dominican Republic", Code="DO"},
                new Countries(){ Name="Ecuador", Code="EC"},
                new Countries(){ Name="Egypt", Code="EG"},
                new Countries(){ Name="El Salvador", Code="SV"},
                new Countries(){ Name="Equatorial Guinea", Code="GQ"},
                new Countries(){ Name="Eritrea", Code="ER"},
                new Countries(){ Name="Estonia", Code="EE"},
                new Countries(){ Name="Ethiopia", Code="ET"},
                new Countries(){ Name="Falkland Islands (Malvinas)", Code="FK"},
                new Countries(){ Name="Faroe Islands", Code="FO"},
                new Countries(){ Name="Fiji", Code="FJ"},
                new Countries(){ Name="Finland", Code="FI"},
                new Countries(){ Name="France", Code="FR"},
                new Countries(){ Name="French Guiana", Code="GF"},
                new Countries(){ Name="French Polynesia", Code="PF"},
                new Countries(){ Name="French Southern Territories", Code="TF"},
                new Countries(){ Name="Gabon", Code="GA"},
                new Countries(){ Name="Gambia", Code="GM"},
                new Countries(){ Name="Georgia", Code="GE"},
                new Countries(){ Name="Germany", Code="DE"},
                new Countries(){ Name="Ghana", Code="GH"},
                new Countries(){ Name="Gibraltar", Code="GI"},
                new Countries(){ Name="Greece", Code="GR"},
                new Countries(){ Name="Greenland", Code="GL"},
                new Countries(){ Name="Grenada", Code="GD"},
                new Countries(){ Name="Guadeloupe", Code="GP"},
                new Countries(){ Name="Guam", Code="GU"},
                new Countries(){ Name="Guatemala", Code="GT"},
                new Countries(){ Name="Guinea", Code="GN"},
                new Countries(){ Name="Guinea-Bissau", Code="GW"},
                new Countries(){ Name="Guyana", Code="GY"},
                new Countries(){ Name="Haiti", Code="HT"},
                new Countries(){ Name="Heard Island and Mcdonald Islands", Code="HM"},
                new Countries(){ Name="Holy See (Vatican City State)", Code="VA"},
                new Countries(){ Name="Honduras", Code="HN"},
                new Countries(){ Name="Hong Kong", Code="HK"},
                new Countries(){ Name="Hungary", Code="HU"},
                new Countries(){ Name="Iceland", Code="IS"},
                new Countries(){ Name="India", Code="IN"},
                new Countries(){ Name="Indonesia", Code="ID"},
                new Countries(){ Name="Iran, Islamic Republic of", Code="IR"},
                new Countries(){ Name="Iraq", Code="IQ"},
                new Countries(){ Name="Ireland", Code="IE"},
                new Countries(){ Name="Israel", Code="IL"},
                new Countries(){ Name="Italy", Code="IT"},
                new Countries(){ Name="Jamaica", Code="JM"},
                new Countries(){ Name="Japan", Code="JP"},
                new Countries(){ Name="Jordan", Code="JO"},
                new Countries(){ Name="Kazakhstan", Code="KZ"},
                new Countries(){ Name="Kenya", Code="KE"},
                new Countries(){ Name="Kiribati", Code="KI"},
                new Countries(){ Name="Korea, Democratic People's Republic of", Code="KP"},
                new Countries(){ Name="Korea, Republic of", Code="KR"},
                new Countries(){ Name="Kuwait", Code="KW"},
                new Countries(){ Name="Kyrgyzstan", Code="KG"},
                new Countries(){ Name="Lao People's Democratic Republic", Code="LA"},
                new Countries(){ Name="Latvia", Code="LV"},
                new Countries(){ Name="Lebanon", Code="LB"},
                new Countries(){ Name="Lesotho", Code="LS"},
                new Countries(){ Name="Liberia", Code="LR"},
                new Countries(){ Name="Libyan Arab Jamahiriya", Code="LY"},
                new Countries(){ Name="Liechtenstein", Code="LI"},
                new Countries(){ Name="Lithuania", Code="LT"},
                new Countries(){ Name="Luxembourg", Code="LU"},
                new Countries(){ Name="Macao", Code="MO"},
                new Countries(){ Name="Macedonia, the Former Yugoslav Republic of", Code="MK"},
                new Countries(){ Name="Madagascar", Code="MG"},
                new Countries(){ Name="Malawi", Code="MW"},
                new Countries(){ Name="Malaysia", Code="MY"},
                new Countries(){ Name="Maldives", Code="MV"},
                new Countries(){ Name="Mali", Code="ML"},
                new Countries(){ Name="Malta", Code="MT"},
                new Countries(){ Name="Marshall Islands", Code="MH"},
                new Countries(){ Name="Martinique", Code="MQ"},
                new Countries(){ Name="Mauritania", Code="MR"},
                new Countries(){ Name="Mauritius", Code="MU"},
                new Countries(){ Name="Mayotte", Code="YT"},
                new Countries(){ Name="Mexico", Code="MX"},
                new Countries(){ Name="Micronesia, Federated States of", Code="FM"},
                new Countries(){ Name="Moldova, Republic of", Code="MD"},
                new Countries(){ Name="Monaco", Code="MC"},
                new Countries(){ Name="Mongolia", Code="MN"},
                new Countries(){ Name="Montserrat", Code="MS"},
                new Countries(){ Name="Morocco", Code="MA"},
                new Countries(){ Name="Mozambique", Code="MZ"},
                new Countries(){ Name="Myanmar", Code="MM"},
                new Countries(){ Name="Namibia", Code="NA"},
                new Countries(){ Name="Nauru", Code="NR"},
                new Countries(){ Name="Nepal", Code="NP"},
                new Countries(){ Name="Netherlands", Code="NL"},
                new Countries(){ Name="Netherlands Antilles", Code="AN"},
                new Countries(){ Name="New Caledonia", Code="NC"},
                new Countries(){ Name="New Zealand", Code="NZ"},
                new Countries(){ Name="Nicaragua", Code="NI"},
                new Countries(){ Name="Niger", Code="NE"},
                new Countries(){ Name="Nigeria", Code="NG"},
                new Countries(){ Name="Niue", Code="NU"},
                new Countries(){ Name="Norfolk Island", Code="NF"},
                new Countries(){ Name="Northern Mariana Islands", Code="MP"},
                new Countries(){ Name="Norway", Code="NO"},
                new Countries(){ Name="Oman", Code="OM"},
                new Countries(){ Name="Pakistan", Code="PK"},
                new Countries(){ Name="Palau", Code="PW"},
                new Countries(){ Name="Palestinian Territory, Occupied", Code="PS"},
                new Countries(){ Name="Panama", Code="PA"},
                new Countries(){ Name="Papua New Guinea", Code="PG"},
                new Countries(){ Name="Paraguay", Code="PY"},
                new Countries(){ Name="Peru", Code="PE"},
                new Countries(){ Name="Philippines", Code="PH"},
                new Countries(){ Name="Pitcairn", Code="PN"},
                new Countries(){ Name="Poland", Code="PL"},
                new Countries(){ Name="Portugal", Code="PT"},
                new Countries(){ Name="Puerto Rico", Code="PR"},
                new Countries(){ Name="Qatar", Code="QA"},
                new Countries(){ Name="Reunion", Code="RE"},
                new Countries(){ Name="Romania", Code="RO"},
                new Countries(){ Name="Russian Federation", Code="RU"},
                new Countries(){ Name="Rwanda", Code="RW"},
                new Countries(){ Name="Saint Helena", Code="SH"},
                new Countries(){ Name="Saint Kitts and Nevis", Code="KN"},
                new Countries(){ Name="Saint Lucia", Code="LC"},
                new Countries(){ Name="Saint Pierre and Miquelon", Code="PM"},
                new Countries(){ Name="Saint Vincent and the Grenadines", Code="VC"},
                new Countries(){ Name="Samoa", Code="WS"},
                new Countries(){ Name="San Marino", Code="SM"},
                new Countries(){ Name="Sao Tome and Principe", Code="ST"},
                new Countries(){ Name="Saudi Arabia", Code="SA"},
                new Countries(){ Name="Senegal", Code="SN"},
                new Countries(){ Name="Serbia and Montenegro", Code="CS"},
                new Countries(){ Name="Seychelles", Code="SC"},
                new Countries(){ Name="Sierra Leone", Code="SL"},
                new Countries(){ Name="Singapore", Code="SG"},
                new Countries(){ Name="Slovakia", Code="SK"},
                new Countries(){ Name="Slovenia", Code="SI"},
                new Countries(){ Name="Solomon Islands", Code="SB"},
                new Countries(){ Name="Somalia", Code="SO"},
                new Countries(){ Name="South Africa", Code="ZA"},
                new Countries(){ Name="South Georgia and the South Sandwich Islands", Code="GS"},
                new Countries(){ Name="Spain", Code="ES"},
                new Countries(){ Name="Sri Lanka", Code="LK"},
                new Countries(){ Name="Sudan", Code="SD"},
                new Countries(){ Name="Suriname", Code="SR"},
                new Countries(){ Name="Svalbard and Jan Mayen", Code="SJ"},
                new Countries(){ Name="Swaziland", Code="SZ"},
                new Countries(){ Name="Sweden", Code="SE"},
                new Countries(){ Name="Switzerland", Code="CH"},
                new Countries(){ Name="Syrian Arab Republic", Code="SY"},
                new Countries(){ Name="Taiwan, Province of China", Code="TW"},
                new Countries(){ Name="Tajikistan", Code="TJ"},
                new Countries(){ Name="Tanzania, United Republic of", Code="TZ"},
                new Countries(){ Name="Thailand", Code="TH"},
                new Countries(){ Name="Timor-Leste", Code="TL"},
                new Countries(){ Name="Togo", Code="TG"},
                new Countries(){ Name="Tokelau", Code="TK"},
                new Countries(){ Name="Tonga", Code="TO"},
                new Countries(){ Name="Trinidad and Tobago", Code="TT"},
                new Countries(){ Name="Tunisia", Code="TN"},
                new Countries(){ Name="Turkey", Code="TR"},
                new Countries(){ Name="Turkmenistan", Code="TM"},
                new Countries(){ Name="Turks and Caicos Islands", Code="TC"},
                new Countries(){ Name="Tuvalu", Code="TV"},
                new Countries(){ Name="Uganda", Code="UG"},
                new Countries(){ Name="Ukraine", Code="UA"},
                new Countries(){ Name="United Arab Emirates", Code="AE"},
                new Countries(){ Name="United Kingdom", Code="GB"},
                new Countries(){ Name="United States", Code="US"},
                new Countries(){ Name="United States Minor Outlying Islands", Code="UM"},
                new Countries(){ Name="Uruguay", Code="UY"},
                new Countries(){ Name="Uzbekistan", Code="UZ"},
                new Countries(){ Name="Vanuatu", Code="VU"},
                new Countries(){ Name="Venezuela", Code="VE"},
                new Countries(){ Name="Viet Nam", Code="VN"},
                new Countries(){ Name="Virgin Islands, British", Code="VG"},
                new Countries(){ Name="Virgin Islands, US", Code="VI"},
                new Countries(){ Name="Wallis and Futuna", Code="WF"},
                new Countries(){ Name="Western Sahara", Code="EH"},
                new Countries(){ Name="Yemen", Code="YE"},
                new Countries(){ Name="Zambia", Code="ZM"},
                new Countries(){ Name="Zimbabwe", Code="ZW"},
            };
            return countriesList;
        }

        public string GetCountryName(string code)
        {
            var country = GetCountriesList().Where(x => x.Code == code);
            if (country == null || country.Count() == 0) return "Unknonwn";
            return country.First().Name;
        }

        public string GetCountryCode(string name)
        {
            var country = GetCountriesList().Where(x => x.Name == name);
            if (country == null || country.Count() == 0) return "SEM CODIGO";
            return country.First().Code;
        }
    }
}