//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteLocalbitcoinsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsernameTrade
    {
        public int UsernameKey { get; set; }
        public decimal Trade_amount { get; set; }
        public string Contact_number { get; set; }
        public System.DateTime Date { get; set; }
        public string Email_used { get; set; }
        public string Trade_Type { get; set; }
        public string Currency { get; set; }
        public Nullable<bool> CardUsed { get; set; }
        public Nullable<int> C4digitscard { get; set; }
    
        public virtual Username Username { get; set; }
    }
}
