//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteLocalbitcoinsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Username
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Username()
        {
            this.UsernameTrades = new HashSet<UsernameTrade>();
        }
    
        public int UsernameKey { get; set; }
        public string Username1 { get; set; }
    
        public virtual UsernameInfo UsernameInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsernameTrade> UsernameTrades { get; set; }
    }
}
